[supervisord]

[program:xvfb]
command=/usr/bin/Xvfb :0 -screen 0 1280x720x24
autorestart=true

[program:qemu]
environment=DISPLAY=:0
command=/usr/bin/qemu-system-x86_64 \
    -m 4096 \
    -smp 4 \
    -hda /opt/android.qcow2 \
    -cdrom /opt/android.iso \
    -boot d \
    -vga virtio
autorestart=false

[program:vnc]
command=/usr/bin/x11vnc -display :0 -forever -nopw
autorestart=true

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autorestart=true
